- .travis.yml
Uses Travis' container based infrastructure for quicker builds.
Also caches bundles between builds for even quicker builds.
> Travis docker

- lib/connection_pool/timed_stack.rb
- test/test_connection_pool_timed_stack.rb
In the case that object creation throws an exception, the `@created` counter was still being incremented, effectively taking up a slot in the pool forever.
> Do not increment `@created` object counter in `TimedStack` before object creation actually succeeds

- Changes.md
- README.md
- lib/connection_pool.rb
- lib/connection_pool/timed_stack.rb
- lib/connection_pool/version.rb
- test/test_connection_pool.rb
The changes in #67 have resulted in unnecessary connection discards when using an explicit return:
```ruby
pool = ConnectionPool.new
pool.with do |conn|
return true
end
```
The explicit return means that the `success = true` line within `with` is not executed.
> Non-local return forces disconnect

- README.md
Here's the quit method in [redis-rb](https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L103-L115).
> Redis-rb doesn't have a close method

- lib/connection_pool/monotonic_time.rb
- lib/connection_pool/timed_stack.rb
Timers using the system clock are inherently buggy. This PR copies the monotonic clock from concurrent-ruby into this gem and uses it for the timers in `TimedStack`. This optimization in concurrent-ruby was [originally suggested by Aaron Patterson](https://github.com/ruby-concurrency/concurrent-ruby/pull/253).
The system clock is bad for timers because it regularly changes: NTP synchronization, VM adjustment, manual change, etc. Monotonic clocks exist specifically for timers and are generally controlled directly by the processor. Modern operating systems all have a monotonic clock, but older versions of Ruby do not provide access to it.
The clock class in this PR detects the availability of a monotonic clock. On Ruby versions where a monotonic clock is available (MRI 2.1 and newer, all …
> Monotonic clock for more accurate timeouts.

- lib/connection_pool.rb
- test/test_connection_pool.rb
I have a Rails app that is mostly using Redis for Sidekiq, but has a couple of other calls to Redis. I'd like to be able to use the same connection pool for these calls and Sidekiq, which would let me have only one Redis connection per thread.
e.g. with a setup like this
```ruby
threads = 5
$redis_pool = ConnectionPool.new(size: threads)
$redis = ConnectionPool::Wrapper.new(pool: $redis_pool)
Sidekiq.configure_client do |config|
config.redis = $redis_pool
end
```
I could have this code in a thread and only have one Redis connection checked in at the end.
```ruby
$redis.ping
MyWorker.perform_async(1, 2, 3)
```
Am I missing something? Could this be useful for ConnectionPool?
> Create wrapper with existing pool

- README.md
- test/test_connection_pool.rb
This issue https://github.com/mperham/connection_pool/issues/94 is already closed by https://github.com/mperham/connection_pool/pull/97 PR. 
But it is unclear to users that they have already opportunity to get stats without accessing instance variables (last comment https://github.com/mperham/connection_pool/issues/94#issuecomment-371143167 is relatively fresh).
This PR updates README and changes some test cases to use public methods instead of internal instance variables.
> add info about stats to README

- test/test_connection_pool.rb
Catch Exceptions in threads used in tests instead of letting them die
from uncaught exception where a warning would be triggered in Ruby >= 2.5
where Thread.report_on_exception enabled by default.
https://bugs.ruby-lang.org/issues/14143
> Don't let threads die from exceptions in tests

- Changes.md
- lib/connection_pool.rb
- test/test_connection_pool.rb
Expose `pool` from `ConnectionPool::Wrapper`
See #113
> mperham/connection_pool#113 expose pool from Wrapper

- .travis.yml
This PR changes the CI matrix to a less-churn style which is auto-updated as and when the `rvm` installation in Travis gets updated.
> CI: Use 2.6, 2.5, 2.4, jruby-9.2.8.0

- lib/connection_pool/timed_stack.rb
`thread` library was removed from Ruby 1.9.
> Removed explicitly declaration of thread library

- README.md
This PR updates a README example to the code which is found in the library.
Redis-rb 4.x dropped the `Redis.connect` method.
I looked around my dependencies for usages, and hit this code on text-searching in my local files.
> README: Use API Redis.new in example

- .travis.yml
This PR updates the CI matrix to use latest JRuby, **9.2.11.1**.
[JRuby 9.2.11.1 release blog post](https://www.jruby.org/2020/03/25/jruby-9-2-11-1.html)
**Update**: I changed the configuration not to point to a release, but to an `rvm` alias.
`rvm` responded with this:
```
$ rvm use jruby --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required jruby-head is not installed - installing.
```
> CI: Run latest JRuby release

- lib/connection_pool/timed_stack.rb
With the introduction of `ConnectionPool::TimeoutError` in https://github.com/mperham/connection_pool/commit/dd5dac56607a146aa29ec4ef557c42726541a2fa the comments have not been changed.
Now they reflect what is being thrown.
PS: I did not search the whole codebase, only saw the mismatch in this file.
> Change comments to use ConnectionPool::TimeoutError

- connection_pool.gemspec
Follow-up to https://github.com/mperham/connection_pool/issues/133
The ruby version check is permissive on purpose, i.e. it will also allow the gem install for Ruby version 3.x. as I am not aware of any problems this gem would have with Ruby 3.x and it will allow people using Ruby 3 beta versions to use this gem.
> Add required_ruby_version to the Gemspec

- lib/connection_pool.rb
- test/test_connection_pool.rb
In Ruby 2.5, [Object#then](https://apidock.com/ruby/v2_6_3/Object/then) was added as a standard way to "yield self" to the caller. This convention is useful since it allows for library maintainers to abstract access to a value.
For example, [Concurrent#Promise](https://ruby-concurrency.github.io/concurrent-ruby/1.1.4/Concurrent/Promise.html) implements `.then` in a way which allow access to a concurrently resolved value:
```ruby
Concurrent::Promise.execute { :foo }.then { |val| puts val } #=> :foo 
:foo.then { |val| puts val } #=> :foo 
```
When using `connection-pool` in the wild, on multiple occasions I have been unable to directly pass a `ConnectionPool` wrapped Redis to a library. Most recently, we [can't use a `ConnectionPool` Redis in …
> RFC: Implement `ConnectionPool#then`

- Changes.md
- README.md
- lib/connection_pool.rb
- lib/connection_pool/timed_stack.rb
- test/test_connection_pool_timed_stack.rb
The implementation of shutdown from #27 does not actually provide for a way for the pool to re-create connections, only render the pool unusable. This implements such a behavior. A new method is added so as to not change the existing behavior of `shutdown`.
> Allow restarting pool

- lib/connection_pool/wrapper.rb
- test/test_connection_pool.rb
The current version of the gem converts keyword args to a hash arg in Ruby 3.0. I changed the tests to cause a warning in Ruby 2.7 and failure in Ruby 3.0 without the fix.
The proposed fix in wrapper.rb is backwards compatible with 2.2.0 (minimum version from the gemspec). 
Alternately, maybe cut a new major version that requires Ruby 2.7+?
Let me know what you think.
> Ruby 3.0: split positional/keyword args

- .github/workflows/ci.yml
Causes the Build to be successful, even when tests on TruffleRuby won't run.
> Mark TruffleRuby experimental in CI

- lib/connection_pool/wrapper.rb
- test/test_connection_pool.rb
Fixes https://github.com/mperham/connection_pool/issues/148.
In Ruby 2.7 keyword arguments are not yet separated from positional ones. `**kwargs` was seemingly introduced here to suppress warnings, but for accuracy we need to remove `**kwargs` and just add `ruby2_keywords`.
> Fix argument forwarding in Ruby 2.7

- lib/connection_pool.rb
Since it's faster and doesn't need to mess with the `$LOAD_PATH`. This is how it was historically done, but it was changed at https://github.com/mperham/connection_pool/commit/dd5dac56607a146aa29ec4ef557c42726541a2fa.
Since changing that seems unrelated to that change, I'd like to go back to `require_relative` if possible.
This is particularly helpful for me as a maintainer of `bundler`, because bundler includes a vendored copy of this library, and we really don't want to mess with the `$LOAD_PATH` at the time we require it. Including this change allows us to vendor the library completely unmodified.
> Prefer `require_relative` for internal requires

- lib/connection_pool/timed_stack.rb
This upstreams this PR to the rubygems repository: https://github.com/rubygems/rubygems/pull/4709.
Using the explicit `Thread` namespace is the future-proof way of accessing these constants.
> Use explicit namespaces for `Mutex` and `ConditionVariable`

- Changes.md
- connection_pool.gemspec
As per https://github.com/mperham/connection_pool/pull/153#issuecomment-876534647.
> Drop support for Ruby 2.2

- lib/connection_pool/wrapper.rb
The problem is:
```
irb(main):001:0> "2.7.0.preview1" >= "2.7.0"
=> true
irb(main):002:0> Gem::Version.new("2.7.0.preview1") >= Gem::Version.new("2.7.0")
=> false
```
This is very minor, and will only solve actual issues when using old prereleases of ruby, which is not great anyways (users should upgrade). But I guess it sets a standard in the code, so that if further checks like this are added in the future, they are done like this, in a way that respects prereleases.
> Use prerelease aware version comparison

- README.md
* I see non-critical and noncritical, but no `non critical`
* ref: https://en.wiktionary.org/wiki/non-critical
minor concern, pls ignore if you find it trival
> Update readme: non critical -> non-critical

- lib/connection_pool.rb
- test/test_connection_pool.rb
Fix: https://github.com/mperham/connection_pool/issues/165
Using connections inherited from a parent process can have very nasty consequences and it's pretty much never desired.
This patch use the `Process._fork` API added in Ruby 3.1 to automatically detect when a fork is happening, and when it does, drop all existing connections.
`ObjectSpace.each_object` is very slow for large applications:
```ruby
[1] pry(main)> Benchmark.realtime { ObjectSpace.each_object(ConnectionPool) { |c| c }.size }
=> 0.06875399989075959
[2] pry(main)> Rails.application.eager_load!
=> nil
[3] pry(main)> Benchmark.realtime { ObjectSpace.each_object(ConnectionPool) { |c| c }.size }
=> 0.14990400010719895
[4] pry(main)> Benchmark.realtime { fork { exit! }}
=> 0.004583500092849135
```
So I'd really recommend to …
> Automatically drop all connections after fork

- connection_pool.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
> Opt-in for MFA requirement

- connection_pool.gemspec
Add `changelog_uri` to the gem metadata.
Changelog URLs have been valid [metadata](https://guides.rubygems.org/specification-reference/#metadata) since 2017 on RubyGems.org. Setting `changelog_uri` will add a "Changelog" link to the Rubygems page for connection_pool https://rubygems.org/gems/connection_pool/
> Set "changelog_uri" in gemspec to point to Changes.md

- lib/connection_pool.rb
- test/test_connection_pool.rb
There was a recent feature to automatically drop all connections after fork. This is quite nice and makes sense.
However, for some rails app that usually don't follow the fork model (like w/ unicorn/puma), and additionally have some logic to fork processes to perform internal business logic that doesn't rely or use `ConnectionPool`, the application can observe Redis connection issues or resets. These forks can happen during application run time. Like ours.
In such a case, it'd be nice to not automatically drop all the connections, since the underlying process isn't working with Redis/ConnectionPool, and as a sideeffect the pool in the primary process is impacted.
This PR proposes a new attribute `auto_reload_after_fork` as a config option. By default it is `true`. However, application …
> Ability to optionally drop all connections after fork

- README.md
- lib/connection_pool.rb
- lib/connection_pool/timed_stack.rb
- test/test_connection_pool.rb
- test/test_connection_pool_timed_stack.rb
There have been several discussions/attempts at adding a idle connection reaping functionality to this gem: https://github.com/mperham/connection_pool/issues/125 https://github.com/mperham/connection_pool/pull/127 https://github.com/mperham/connection_pool/pull/126
I and many others would find value in adding this functionality however I am in agreement with the previous discussions that the key to adding this `reap` functionality is to add it in a way that keeps the simplicity of this gem.
In order to accomplish this, I've added two new public methods to `ConnectionPool` (as well as matching methods for `TimedStack`):
1. `#idle` - Returns how many connections that are created and available in the pool. This is different than `available` because `available` includes connections that …
> Add reap functionality

- .github/workflows/ci.yml
While default autofix is handy, the configuration makes it so that auto-fixable issues don't trigger a CI failure. I ran into this on some other projects.
> Make automatically fixable standard issues fail CI

- lib/connection_pool/timed_stack.rb
- test/test_connection_pool.rb
- test/test_connection_pool_timed_stack.rb
NOTE: This includes the commit from #188 so I didn't have to deal with wonky rebasing.
This limits the mutex lock to interactions with the stack that are small, fast, and atomic. Moving the connection close code outside the mutex as it doesn't impact the pool.
Sidenote: Thinking about releasing the reap update, it probably needs to be a major version bump as it breaks things for anyone that has used the defined extension points and interacts with `@que`. It is probably possible this could be modified to only introduce a breaking change if `reap` is used.
> Avoid extra mutex contention

- lib/connection_pool/timed_stack.rb
- test/test_connection_pool.rb
- test/test_connection_pool_timed_stack.rb
There appears to be a small bug around `ConnectionPool#reload` where it is possible to create more connections than the size of the pool if you run `reload` while a connection is checked out.
See the test cases defined in https://github.com/mperham/connection_pool/pull/192/commits/4f4e5f6b28eef2ac3d07827f86bbbae0a0570c96
These test cases all fail on the master branch. This is due to how `@created` instance variable in `ConnectionPool::TimedStack` is decremented, where currently it is set to 0 on `#shutdown(reload: true)` even if no connections were "shutdown" on the reload.
> Track checked out created connections across reloads
